### PR TITLE
Encode all Ampersands

### LINKED ISSUE #110: & written instead of &amp;
**Describe the bug**

When I export the following string to XML:

`Hello & world today; or tomorrow`

The XML that I get is:

`<text>Hello & world today; or tomorrow</text>`

This is invalid, because the `&` must be encoded as `&amp;`

**To Reproduce**
Export the string `Hello & world today; or tomorrow` to XML.

**Expected behavior**
Expected value: `<text>Hello &amp; world today; or tomorrow</text`

**Version:**
 - node.js: [14.17.4]
 - xmlbuilder2 [3.0.2]

**Additional context**
I suspect that the root cause is that the parser has a regular expression that assumes that all in between the `&` and `;` are treated as an entity. 
In the example above, if you'd remove the semicolon, it will export

### PR DESCRIPTION
**Pull request by coffeemakr**
The current regex for replacing ampersands has a flawed check to see if the ampersand is used HTML-encoded character. The regex isn't working because it ignores whitespace between the `&` and the `;` character.  Also I don't think it's the responsibility of the writer to interpret if a value has been encoded already.

Fixes #110 and #109

**Type of change**:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

### CODE REVIEW

**Comment by andrenarchy** [comment]
We encounter the same problem and would be grateful if this gets merged!

File: src/writers/BaseWriter.ts [hunk 1]
```diff
@@ -928,7 +928,7 @@ export abstract class BaseWriter<T extends BaseWriterOptions, U extends XMLSeria
      * 5. Replace any occurrences of ">" in markup by "&gt;".
      * 6. Return the value of markup.
      */
-    const markup = node.data.replace(/(?!&([^&; ]*);)&/g, '&amp;')
+    const markup = node.data.replace(/&/g, '&amp;')
```
Comment (chris-rudmin) [inline src/writers/BaseWriter.ts:931]: FYI, this fix will double encode already html encoded entities `&amp;` => `&amp;amp;`

Comment (chris-rudmin) [reply src/writers/BaseWriter.ts:931]: Probably better to fix the regex with a negative lookahead `/&(?!amp;)/g`

**Comment by vanstinator** [comment]
We're hitting this as well. Happy to scrub in here to get this over the finish line.

**Comment by jgrubb16** [comment]
Also made some additions in #154. All tests now passing.
