### PR TITLE
Correct output falsy values from object

### LINKED ISSUE #21: Number 0 is omitted when converting object to xml
**Describe the bug**
When converting object to xml, it's not expected to convert number `0` into empty content.

**To Reproduce**

```js
const { create } = require('xmlbuilder2');

const xml = create().ele({ value: 0 }).end()
```

will produce

```xml
<?xml version="1.0"?><root><value/></root>
```

**Expected behavior**

It should be

```xml
<?xml version="1.0"?><root><value>0</value></root>
```

**Version:**
 - node.js: [12.13.0]
 - xmlbuilder2 [2.1.2]

**Additional context**

### PR DESCRIPTION
**Pull request by linkeo**
Fixes #21

### CODE REVIEW

**Comment by linkeo** [comment]
@oozcitak please check the code. `null`, `undefined`, `''` will still be omitted, but `0` and `false` will be visible in xml.

File: src/builder/XMLBuilderImpl.ts [hunk 1]
```diff
@@ -168,7 +168,7 @@ export class XMLBuilderImpl implements XMLBuilder {
 
           // expand child nodes under parent
           lastChild.ele(val)
-        } else if (val) {
+        } else if (val != null && val !== '') {
```
Comment (oozcitak) [inline src/builder/XMLBuilderImpl.ts:171]: Can you please remove `val !== ''`. I don't see any reason to not allow empty text nodes.

Comment (linkeo) [reply src/builder/XMLBuilderImpl.ts:171]: Sorry to be late.

When I was testing this script:

```js
const builder = require('xmlbuilder2');

[
  { headless: true, allowEmptyTags: false },
  { headless: true, allowEmptyTags: true },
].map(options => {
  const xml = builder
    .create()
    .ele({ value: '' })
    .end(options);
  console.log(options);
  console.log(xml);
});
```

I got this result using `val != null`:

```txt
{ headless: true, allowEmptyTags: false, format: 'xml' }
<value></value>
{ headless: true, allowEmptyTags: true, format: 'xml' }
<value></value>
```

And got this result using `val != null && val !== ''`:

```txt
{ headless: true, allowEmptyTags: false, format: 'xml' }
<value/>
{ headless: true, allowEmptyTags: true, format: 'xml' }
<value></value>
```

I thought the latter situation will meet my expectation.
